language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -e .[develop]

before_script:
  - pycodestyle pyls_cwrap
  - flake8 pyls_cwrap
  - mypy pyls_cwrap

script:
  - pytest
